### ISSUE TITLE
Add a prop of local wasm file url or at least baseURL 

### ISSUE THREAD

**Issue by vitpankin** [georgestagg/pandoc-wasm#1]
Impossible to tune local path, so local fetch always fails

**Comment by georgestagg** [comment]
There is now a Pandoc for WebAssembly engine built using the GHC Wasm backend. https://github.com/tweag/pandoc-wasm

I'm going to archive this project (closing this thread). I would recommend trying out Tweag's new pandoc-wasm project to see if it supports your needs!
